### ISSUE TITLE
[김민우] 7 segment countdown

### ISSUE THREAD

**Issue by Sunset-Kim** [FC-InnerCircle/fe1-library#3]
## 프로젝트 이름

7 segment display , 카운트다운 컴포넌트 

## 개요

- 7 segment display를 통해 target 날짜까지 카운트다운 하는 라이브러리

## 저장소 주소
[저장소 주소](https://github.com/Sunset-Kim/7segment-countdown)

## npm 주소
[@7segment/core](https://www.npmjs.com/package/@7segment/core)
[@7segment/countdown-react](https://www.npmjs.com/package/@7segment/countdown-react)

## 체크리스트

- [x] 개인 저장소 생성
- [x] README.md 파일 작성 (다음 항목 포함)
  - [x] 프로젝트 개요
  - [x] 설치 방법 / 사용 방법
  - [x] 라이선스 표기
- [x] 기능 구현
- [x] 테스트 추가 (라인 커버리지 60% 이상)
- [x] 사용 예제 프로젝트 추가 (examples 폴더 아래에 2개 이상)
- [x] npm 퍼블리싱

## Milestone
- [x] segment core 함수를 정의합니다
- [x] React 7 segment display 를 만듭니다
- [x] React CountDown  만듭니다.

## 추가피드백
- [x] LCD 시계처럼 svg 콜론, 점을 추가
- [x] 사용법을 편리하게 하기위해서 target date를 memorize 하자
- [x] 리드미 문서에 props와 return에 대한 설명을 충실히 하자
- [x] 듀레이션 숫자를 ms 단위로 number type으로 받게하자
- [x] 유저가 countdown에 children을 넘기지 않더라도 전체스타일을 사용가능하게 하자
- [x] 불필요하게 길어지는 props 이름을 간소화 하자 (segmentOnColor => onColor) 
- [x] magic number를 피하자 : SEC_IN_MS 를 상수 처리  
- [ ] segemnt map 을 core 에서 export 해주지 않도록 처리
- [x] 불필요한 export를 제거한다
